<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="KPBAEK" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style01 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'굴림'; font-size:10pt; background-color:#CCCCFF }
	  
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
body { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
</style>
	<table border="1" cellpadding="0" cellspacing="0" id="sheet0" style="width: 210mm;">
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<col class="col4">
		<col class="col5">
		<col class="col6">
		<col class="col7">
		<col class="col8">
		<col class="col9">
		<col class="col10">
		<col class="col11">
		<col class="col12">
		<col class="col13">
		<col class="col14">
		<col class="col15">
		<col class="col16">
		<col class="col17">
		<col class="col18">
		<col class="col19">
		<col class="col20">
		<col class="col21">
		<col class="col22">
		<col class="col23">
		<col class="col24">
		<tbody>
		  <tr>
			<td align=center colspan="10" rowspan="2" width="55%"><b>생산의뢰서</b></td>
			<td width=5% rowspan="2">의<br />
뢰</td>
			<td colspan="2" width=10%>담당</td>
			<td colspan="2" width=10%>팀장</td>
			<td colspan="2" width=10%>이사</td>
			<td colspan="2" width=10%>대표이사</td>
		  </tr>
		  <tr height=70px>
		  	<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
		  </tr>
		  <tr>
			<td colspan="3" width=15% class="style01">문서번호</td>
			<td colspan="5" width="25%"></td>
			<td colspan="2" width=10%>P/I NO. </td>
			<td colspan="3"></td>
			<td colspan="2">작성일</td>
			<td colspan="4"></td>
		  </tr>
		  <tr>
			<td colspan="3" width=10%>바이어</td>
			<td colspan="10" width="30%"></td>
			<td colspan="2">P/O NO.</td>
			<td colspan="4"></td>
		  </tr>
		  <tr>
			<td colspan="3" width=10%>MODEL</td>
			<td colspan="10" width="30%"></td>
			<td colspan="2">Q'TY</td>
			<td colspan="4"></td>
		  </tr>
		  <tr>
			<td rowspan=2 colspan="3">CURRENCY</td>
			<td>C1</td>
			<td>C2</td>
			<td width=5%>C3</td>
			<td width=5%>C4</td>
			<td width=5%>C5</td>
			<td width=5%>C6</td>
			<td width=5%>C7</td>
			<td width=5%>C8</td>
			<td width=5%>C9</td>
			<td>C10</td>
			<td>C11</td>
			<td>C12</td>
			<td>C13</td>
			<td>C14</td>
			<td>C15</td>
			<td>기타</td>
		  </tr>
			<td>RSD</td>
			<td>EUR</td>
			<td width=5%>USD</td>
			<td width=5%>GBP</td>
			<td width=5%>CHF</td>
			<td width=5%></td>
			<td width=5%></td>
			<td width=5%></td>
			<td width=5%></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		  </tr>
		  <tr>
			<td colspan="3">Fitness</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td></td>
		  </tr>
		  <tr>
			<td rowspan=2 colspan="3">SERIAL NUMBER</td>
			<td colspan=2>SRL</td>
			<td colspan=2>P-OCR</td>
			<td colspan=2>S-OCR</td>
			<td>C1</td>
			<td>C2</td>
			<td>C3</td>
			<td>C4</td>
			<td>C5</td>
			<td colspan=5>기타</td>
		  </tr>
		  <tr>
			<td colspan=2>X</td>
			<td colspan=2>X</td>
			<td colspan=2>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td>X</td>
			<td colspan=5></td>
		  </tr>
		  <tr>
			<td rowspan=2 colspan="3">CF DETECTOR</td>
		    <td colspan=2>UV</td>
			<td colspan=2>MG</td>
			<td colspan=2>MRA</td>
			<td colspan=2>IR</td>
			<td colspan=3>Tape Detector</td>
			<td colspan=5>기타</td>
		  </tr>
		  <tr>
		    <td colspan=2>X</td>
			<td colspan=2>X</td>
			<td colspan=2>X</td>
			<td colspan=2>X</td>
			<td colspan=3>X</td>
			<td colspan=5></td>
		  </tr>
		  <tr>
			<td rowspan=10 colspan="2">OPTION</td>
			<td rowspan=2>SW</td>
			<td colspan=4>ISSUE</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=4>SNC</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td rowspan=7>HW</td>
			<td colspan=4>CIS</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=4>LAN</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td rowspan=2 colspan=2>Reject <br />Pocket</td>
			<td colspan=2>Old Type</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=2>New Type</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=4>Printer</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=4>SV-200</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td colspan=4>SDP-7</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td>기타</td>
			<td colspan=4>특이사항</td>
			<td colspan=12></td>
		  </tr>
		  <tr>
			<td rowspan=5 colspan="3">USER OPTION</td>
		    <td colspan=4>Language (LCD)</td>
			<td colspan=13></td>
		  </tr>
		  <tr>
		    <td colspan=4>Out Box</td>
			<td colspan=13></td>
		  </tr>
		  <tr>
		    <td colspan=4>Label</td>
			<td colspan=13></td>
		  </tr>
		  <tr>
		    <td colspan=4>PWR/                  Printer Power Cable</td>
			<td colspan=13></td>
		  </tr>
		  <tr>
		    <td colspan=4>User's Manual</td>
			<td colspan=13></td>
		  </tr>
		  <tr>
			<td colspan="3">기본 악세서리</td>
		    <td colspan=16>Cleaning Brush, Clean Cloth, PC Cable</td>
		  </tr>
		  <tr>
			<td colspan="3">품질 이관일</td>
		    <td colspan=6></td>
			<td colspan="3">품질 출하일</td>
		    <td colspan=7></td>
		  </tr>
		  <tr>
			<td align=center colspan="10" rowspan="2" width="55%"></td>
			<td width=5% rowspan="2">품<br/>질</td>
			<td colspan="2" width=10%>담당</td>
			<td colspan="2" width=10%>차장</td>
			<td colspan="2" width=10%>부장</td>
			<td colspan="2" width=10%>팀장</td>
		  </tr>
		  <tr height=70px>
		  	<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
		  </tr>
		  <tr>
			<td align=center colspan="10" rowspan="2" width="55%"></td>
			<td width=5% rowspan="2">연<br/>구<br/>소</td>
			<td colspan="2" width=10%>담당</td>
			<td colspan="2" width=10%>과장</td>
			<td colspan="2" width=10%>부장</td>
			<td colspan="2" width=10%>이사</td>
		  </tr>
		  <tr height=70px>
		  	<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
		  </tr>
		  <tr>
			<td align=center colspan="10" rowspan="2" width="55%"></td>
			<td width=5% rowspan="2">구<br/>매</td>
			<td colspan="2" width=10%>담당</td>
			<td colspan="2" width=10%>차장</td>
			<td colspan="2" width=10%>부장</td>
			<td colspan="2" width=10%>이사</td>
		  </tr>
		  <tr height=70px>
		  	<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
		  </tr>
		  		  <tr>
			<td align=center colspan="10" rowspan="2" width="55%"></td>
			<td width=5% rowspan="2">생<br/>산</td>
			<td colspan="2" width=10%>담당</td>
			<td colspan="2" width=10%>과장</td>
			<td colspan="2" width=10%>부장</td>
			<td colspan="2" width=10%>이사</td>
		  </tr>
		  <tr height=70px>
		  	<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
			<td colspan="2">1</td>
		  </tr>
		  <tr>
			<td colspan="4">SBM-영업-P-701-05</td>
		    <td colspan=12>㈜에스비엠</td>
			<td colspan=3>A4(210 X297mm)</td>
		  </tr>
		  </tbody>
	</table>
  </body>
</html>
