<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="KPBAEK" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style1 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style2 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style3 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:2px solid #BFBFBF !important; border-left:2px solid #BFBFBF !important; border-right:2px solid #BFBFBF !important; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style4 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style5 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:2px solid #BFBFBF !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style6 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:2px solid #BFBFBF !important; border-left:2px solid #BFBFBF !important; border-right:2px solid #BFBFBF !important; color:#A5B6CA; font-family:'맑은 고딕'; font-size:9pt; background-color:white }
	  td.style7 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:10pt; background-color:white }
	  td.style8 { vertical-align:bottom; border-bottom:none #000000; border-top:2px solid #BFBFBF !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style9 { vertical-align:bottom; border-bottom:none #000000; border-top:2px solid #BFBFBF !important; border-left:2px solid #BFBFBF !important; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style10 { vertical-align:bottom; border-bottom:none #000000; border-top:2px solid #BFBFBF !important; border-left:none #000000; border-right:2px solid #BFBFBF !important; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style11 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:none #000000; border-left:2px solid #BFBFBF !important; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style12 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #BFBFBF !important; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style13 { vertical-align:bottom; border-bottom:2px solid #BFBFBF !important; border-top:2px solid #BFBFBF !important; border-left:2px solid #BFBFBF !important; border-right:2px solid #BFBFBF !important; color:#0C0C0C; font-family:'맑은 고딕'; font-size:9pt; background-color:white }
	  td.style14 { vertical-align:bottom; border-bottom:none #000000; border-top:2px solid #BFBFBF !important; border-left:2px solid #BFBFBF !important; border-right:none #000000; color:#A5B6CA; font-family:'맑은 고딕'; font-size:9pt; background-color:white }
	  td.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  table.sheet0 col.col0 { width:83.36666571pt }
	  table.sheet0 col.col1 { width:12.19999986pt }
	  table.sheet0 col.col2 { width:66.42222146pt }
	  table.sheet0 col.col3 { width:102.34444327pt }
	  table.sheet0 tr { height:15pt }
	  table.sheet0 tr.row2 { height:17.25pt }
	  table.sheet0 tr.row3 { height:17.25pt }
	  table.sheet0 tr.row4 { height:4.5pt }
	  table.sheet0 tr.row5 { height:17.25pt }
	  table.sheet0 tr.row6 { height:5.25pt }
	  table.sheet0 tr.row7 { height:17.25pt }
	  table.sheet0 tr.row8 { height:5.25pt }
	  table.sheet0 tr.row10 { height:17.25pt }
	  table.sheet0 tr.row11 { height:4.5pt }
	  table.sheet0 tr.row12 { height:17.25pt }
	  table.sheet0 tr.row13 { height:5.25pt }
	  table.sheet0 tr.row14 { height:17.25pt }
	  table.sheet0 tr.row15 { height:3.75pt }
	  table.sheet0 tr.row16 { height:17.25pt }
	  table.sheet0 tr.row17 { height:4.5pt }
	  table.sheet0 tr.row19 { height:17.25pt }
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
body { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
</style>
	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<tbody>
		  <tr class="row0">
			<td class="column0 style0 s">Please fill in your details below. Local distributor will contact you soon.</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row1">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row2">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style1 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row3">
			<td class="column0 style0 s">Name</td>
			<td class="column1 style2 s"><sup>★</sup></td>
			<td class="column2 style3 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row4">
			<td class="column0">&nbsp;</td>
			<td class="column1 style4 null"><sup></sup></td>
			<td class="column2 style5 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row5">
			<td class="column0 style0 s">Company</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style3 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row6">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style5 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row7">
			<td class="column0 style0 s">Business type</td>
			<td class="column1 style2 s"><sup>★</sup></td>
			<td class="column2 style6 s">Select</td>
			<td class="column3 style7 s">드롭박스. Bank, Cash centre, CIT, Distributor, Gaming, Retailer, Other</td>
		  </tr>
		  <tr class="row8">
			<td class="column0">&nbsp;</td>
			<td class="column1 style4 null"><sup></sup></td>
			<td class="column2 style8 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row9">
			<td class="column0 style0 s">Address</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style9 null"></td>
			<td class="column3 style10 null"></td>
		  </tr>
		  <tr class="row10">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style11 null"></td>
			<td class="column3 style12 null"></td>
		  </tr>
		  <tr class="row11">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row12">
			<td class="column0 style0 s">Country</td>
			<td class="column1 style2 s"><sup>★</sup></td>
			<td class="column2 style13 s">Select</td>
			<td class="column3 style0 s">드롭박스. 국가리스트 시트 첨부합니다. 인터넷에서 찾은 자료이니, 사용하시던 것이 있으면, 다른 것을 이용하셔도 무관합니다.</td>
		  </tr>
		  <tr class="row13">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row14">
			<td class="column0 style0 s">Email address</td>
			<td class="column1 style2 s"><sup>★</sup></td>
			<td class="column2 style3 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row15">
			<td class="column0">&nbsp;</td>
			<td class="column1 style2 null"><sup></sup></td>
			<td class="column2 style1 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row16">
			<td class="column0 style0 s">Telephone number</td>
			<td class="column1 style2 s"><sup>★</sup></td>
			<td class="column2 style3 null"></td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row17">
			<td class="column0">&nbsp;</td>
			<td class="column1 style2 null"><sup></sup></td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row18">
			<td class="column0 style0 s">Comments</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style14 s">Please comment interesting model name.</td>
			<td class="column3 style10 null"></td>
		  </tr>
		  <tr class="row19">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style11 null"></td>
			<td class="column3 style12 null"></td>
		  </tr>
		  <tr class="row20">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row21">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row22">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		  <tr class="row23">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2 style15 s">Submit</td>
			<td class="column3">&nbsp;</td>
		  </tr>
		</tbody>
	</table>
  </body>
</html>
